version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_ADDER=postgres
      - DB_PORT=5432
      - KEYCLOAK_HTTPS_ENABLED=true
    ports:
      - "8080:8080"
    networks:
      - auth_net
    volumes:
      - keycloak_data:/opt/jboss/keycloak/data
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog
    networks:
      - auth_net
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - auth_net
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  keycloak_data:
  postgres_data:
networks:
  auth_net:
    driver: bridge
