server:
  port: 8132
  servlet:
    context-path: /api/integration

spring:
  profiles:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/AuthB2
jwt:
  auth:
    converter:
      resource-id: authClientId

keycloak:
  realm: AuthB2
  domain: localhost:8080
  adminClientId: admin-cli
  adminClientSecret: tClZUM5repAOiO5NbLbVuytjA0beEJZ0
  client: authClientId
  urls:
    auth: http://${keycloak.domain}
